def raise_exception():
    raise Exception("EXCEPTION!")
